name: wechat_camera_picker
version: 4.0.3
publish_to: none
description: |
  A camera picker for Flutter projects based on WeChat's UI,
  which is also a separate runnable extension to the
  wechat_assets_picker.
topics:
  - picker
  - camera
  - image
  - video
  - wechat

repository: https://github.com/fluttercandies/flutter_wechat_camera_picker
issue_tracker: https://github.com/fluttercandies/flutter_wechat_camera_picker/issues

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.10.0
  camera_platform_interface: ^2.1.5
  path: ^1.8.0
  photo_manager:
    path: ../flutter_photo_manager
  video_player: ^2.7.0

dev_dependencies:
  flutter_lints: any
